// src/mocks/mockData.ts

/**
 * Mock Data for Development and Testing
 *
 * This file contains sample workout and meal plan data that matches the structure
 * of plans generated by the OpenAI API. These templates are used for:
 *
 * 1. Development when the backend API is unavailable
 * 2. Testing UI components with consistent data
 * 3. Providing offline functionality as a fallback
 * 4. Demonstrating the expected data structure
 *
 * The structure must be kept in sync with the API response format to ensure
 * consistent rendering throughout the application.
 */

/**
 * Sample workout plan data
 * Structured to match the format returned by the OpenAI-powered Edge Function
 */
export const sampleWorkoutPlan = {
  weeklyPlan: [
    {
      day: "Day 1",
      focus: "Upper Body Strength",
      exercises: [
        {
          name: "Bench Press",
          sets: "4",
          reps: "8-10",
          rest: "90 seconds",
          notes: "Focus on controlled eccentric phase"
        },
        {
          name: "Pull-ups",
          sets: "3",
          reps: "8-12",
          rest: "90 seconds",
          notes: "Use assistance if needed"
        },
        {
          name: "Shoulder Press",
          sets: "3",
          reps: "10-12",
          rest: "60 seconds",
          notes: "Maintain neutral spine"
        },
        {
          name: "Bent-over Rows",
          sets: "3",
          reps: "10-12",
          rest: "60 seconds",
          notes: "Keep back flat"
        }
      ],
      warmup: "5 minutes light cardio, dynamic stretching for shoulders and chest",
      cooldown: "Static stretching for upper body, 5 minutes",
      duration: "45-60 minutes"
    },
    {
      day: "Day 2",
      focus: "Lower Body Strength",
      exercises: [
        {
          name: "Squats",
          sets: "4",
          reps: "8-10",
          rest: "120 seconds",
          notes: "Focus on depth and knee alignment"
        },
        {
          name: "Romanian Deadlifts",
          sets: "3",
          reps: "10-12",
          rest: "90 seconds",
          notes: "Maintain flat back"
        },
        {
          name: "Walking Lunges",
          sets: "3",
          reps: "12 per leg",
          rest: "60 seconds",
          notes: "Step forward with control"
        },
        {
          name: "Calf Raises",
          sets: "3",
          reps: "15-20",
          rest: "45 seconds",
          notes: "Full range of motion"
        }
      ],
      warmup: "5 minutes light cardio, dynamic stretching for hips and legs",
      cooldown: "Static stretching for lower body, 5 minutes",
      duration: "45-60 minutes"
    }
  ],
  periodization: "Linear progression with increasing intensity every 3 weeks",
  progressionStrategy: "Add weight when you can complete all sets at the upper rep range with good form",
  adaptationGuidelines: "If experiencing excessive soreness, reduce volume by 20% for the next session. If plateauing, introduce variable resistance or change rep schemes."
};

/**
 * Sample meal plan data
 * Structured to match the nutrition plan format returned by the OpenAI-powered Edge Function
 * Includes calorie targets, macronutrient breakdowns, and sample meals with ingredients
 */
export const sampleMealPlan = {
  dailyCalories: "2,500 calories",
  macroBreakdown: {
    protein: "180g (30%)",
    carbs: "250g (40%)",
    fats: "85g (30%)"
  },
  mealPlan: [
    {
      meal: "Breakfast",
      time: "7:00 AM",
      options: [
        {
          name: "Protein Oatmeal",
          ingredients: ["1 cup rolled oats", "1 scoop protein powder", "1 tbsp almond butter", "1 banana", "Cinnamon"],
          macros: {
            calories: "450",
            protein: "30g",
            carbs: "60g",
            fats: "12g"
          }
        }
      ]
    },
    {
      meal: "Lunch",
      time: "12:00 PM",
      options: [
        {
          name: "Chicken & Quinoa Bowl",
          ingredients: ["6oz grilled chicken breast", "1 cup cooked quinoa", "Mixed vegetables", "1 tbsp olive oil", "Herbs and spices"],
          macros: {
            calories: "550",
            protein: "45g",
            carbs: "45g",
            fats: "18g"
          }
        }
      ]
    },
    {
      meal: "Dinner",
      time: "6:30 PM",
      options: [
        {
          name: "Salmon with Sweet Potato",
          ingredients: ["6oz salmon fillet", "1 medium sweet potato", "2 cups roasted vegetables", "1 tbsp coconut oil", "Herbs and spices"],
          macros: {
            calories: "520",
            protein: "35g",
            carbs: "40g",
            fats: "25g"
          }
        }
      ]
    }
  ],
  hydrationGuidelines: "Drink 3-4 liters of water daily, increasing intake during training days",
  supplementRecommendations: "Consider whey protein for recovery, creatine monohydrate for strength, and fish oil for general health",
  nutrientTimingStrategies: "Consume protein and carbs within 30 minutes post-workout. Distribute protein intake evenly throughout the day",
  adaptationGuidelines: "Adjust calorie intake based on weight changes and energy levels. Increase carbs on training days if needed."
};
