
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykgceurbedpusquqepdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZ2NldXJiZWRwdXNxdXFlcGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDIzMDMsImV4cCI6MjA2MDQ3ODMwM30.JrTGuh-KI9GPBIYgFHvcnVUB4fP4GKhj-wqCrXedtNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper functions for type-safe data access
export const getProfile = async (userId: string) => {
  const { data, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', userId)
    .single();
  
  if (error) throw error;
  return data;
};

// Helper functions for the sports table
export const getSports = async () => {
  const { data, error } = await supabase
    .from('sports')
    .select('*');
  
  if (error) throw error;
  return data;
};

// Helper functions for the exercises table
export const getExercises = async () => {
  const { data, error } = await supabase
    .from('exercises')
    .select('*');
  
  if (error) throw error;
  return data;
};

// Helper function for workout plans
export const getWorkoutPlans = async (userId: string) => {
  const { data, error } = await supabase
    .from('workout_plans')
    .select('*')
    .eq('user_id', userId);
  
  if (error) throw error;
  return data;
};

// Helper function for workout sessions
export const getWorkoutSessions = async (userId: string) => {
  const { data, error } = await supabase
    .from('workout_sessions')
    .select('*')
    .eq('user_id', userId);
  
  if (error) throw error;
  return data;
};

// Helper function for nutrition logs
export const getNutritionLogs = async (userId: string) => {
  const { data, error } = await supabase
    .from('nutrition_logs')
    .select('*')
    .eq('user_id', userId);
  
  if (error) throw error;
  return data;
};
