// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykgceurbedpusquqepdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZ2NldXJiZWRwdXNxdXFlcGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDIzMDMsImV4cCI6MjA2MDQ3ODMwM30.JrTGuh-KI9GPBIYgFHvcnVUB4fP4GKhj-wqCrXedtNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);